# -*- coding: utf-8 -*-
"""lab2_numpy_pandas

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rpIHf0g0xcMEzXzYXpLUnx0O8fovCL5H
"""

!pip3 install numpy

import numpy as np
one_dim_arr = np.array ([1,2,3,5,7,9,10])
print (one_dim_arr)
print (one_dim_arr.ndim)
print (one_dim_arr.shape)
print (one_dim_arr.size)
print (one_dim_arr.dtype)

two_dim_arr = np.array([[1,2], [3,4], [5,6], [7,8]])
print (two_dim_arr)
print (two_dim_arr.ndim)
print (two_dim_arr.shape)
print (two_dim_arr.size)
print (two_dim_arr.dtype)

the_dim_arr = np.array([[[1,2], [3,4]], [[5,6], [7,8]]])    #퀴즈
print (the_dim_arr)
print (the_dim_arr.ndim)
print (the_dim_arr.shape)
print (the_dim_arr.size)
print (the_dim_arr.dtype)

rand_arr1 = np.random.rand(10)
print (rand_arr1)

rand_arr2 = np.random.rand(5,3)         #퀴즈
print (rand_arr2)

randn1 = np.random.randn(10)
print (randn1)

randn1 = np.random.randn(5,3)
print (randn1)

randint_arr1 = np.random.randint (5, 10, size=5)
print (randint_arr1)

randint_arr2 = np.random.randint (100,150 ,size = 10)
print (randint_arr2)

linspace_arr = np.linspace(0,100,num =5)
print (linspace_arr)

logspace_arr = np.logspace(1,10, num=10,base=2)
print (logspace_arr)

logspace_arr = np.logspace(1,10, num=10,base=10)
print (logspace_arr)

arr = np.random.randn(5,4)
print(arr)

zero_arr = np.zeros(10)
print(zero_arr)

zero_arr = np.zeros((10,2))
print(zero_arr)

zero_arr = np.ones(10)
print(zero_arr)

zero_arr = np.ones((10,5))
print(zero_arr)



eye_arr = np.eye(5)
print (eye_arr)

x = np.random.randint(1,10,size=10)
print(x)

print(x+1)
print(x-1)
print(x *2)
print(x //2)
print(x ** 2)
print(x%2)
print(1/x)

x=np.random.randint(1,10,size=10)
y=np.random.randint(1,10,size=10)
print (x)
print (y)

print(np.add(x,y))
print(np.subtract(x,y))
print(np.multiply(x,y))
print(np.divide(x,y))
print(np.maximum(x,y))
print(np.minimum)

x = np.random.randn(10)
print (x)

print(x[3:])

print (x[3])

print(x[:])

x = np.random.randn(5,4)            #퀴즈3
print (x)

print (x[3:, ])

print (x[:, 2])

arr = np.random.rand(10,5)
print (arr[1:5,2:5])
print (arr[:6,3:])

x = np.random.rand(10)
print (x)

print (np.min(x))
print (np.max(x))
print (np.mean(x))
print (np.std(x))

x = np.random.rand(4,2)
print (x)

print (x,T)

print (np.dot(x, x.T))

x = np.random.randn(10,5)       #퀴즈4
y = np.random.rnadn(5,20)
print (np.dot(x,y))

!pip install pandas

import pandas as pd

stu_dict = {'국어':[90,20,50],
            '수학':[45,50,30]
            ,'영어':[50,30,20]}
stu_data = pd.DataFrame(stu_dict)
print (stu_data)

stu_data = pd.DataFrame(stu_dict,index=['승훈', '준영', '종우'])
print (stu_data)

ex_dict = {"2018":[51,56,78,12,98],         #퀴즈5
           "2019":[5,8,3,10,11],
           "2020":[12,15,86,25],
           "2021":[4,2,8,1,65]}
ex_data = pd.DataFrame(ex_dict, index=['한국','중국','미국','영국','러시아'])
print (ex_data)

print(stu_data)

stu_data.loc['소현'] = [59,80,100]
print(stu_data)

stu_data = stu_data.drop(['준영'])
print (stu_data)

stu_data['과학'] = [50,60,20]
print (stu_data)

stu_data = stu_data.drop(['수학'], axis=1)

stu_data.loc['철수'] = [52,81,87]
stu_data.loc['영희'] = [54,85,48]
stu_data.loc['호동'] = [90,88,55]
print (stu_data)

print (stu_data.iloc[:2])

print (stu_data.iloc[:4,2])         #퀴즈6

print(stu_data[stu_data["영어"] > 80])

print (stu_data[stu_data["영어"] > 80]) & (stu_data["과학"] > 80)   #퀴즈7

print (stu_data.sort_values('과학',ascending=True))

print (stu_data.max())

print(stu_data.min())

print (stu_data.max(axis=1))        #퀴즈8

print (stu_data.sum)

print(stu_data.mean)

print(stu_data.describe())

"""학생별 평점"""

print (stu_data.mean(axis=1))

print (stu_data)

stu_data.to_csv("studata_ex.csv")

read_data = pd.read_csv("studata_ex.csv",sep=",")
print (read_data)

read_data = pd.read_csv("studata_ex.csv",sep=",",index_col = 0)
print (read_data)